# Generated by Django 4.2.5 on 2023-09-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_point_lat_alter_job_point_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='point_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='point_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
